### PR TITLE
implemented best practices and updated methods to remove deprecated func...

### PR DESCRIPTION
**Pull request by wordsforthewise**
...tions and classes (select -> xpath and BaseSpider -> Spider and Selector)

### CODE REVIEW

**Comment by mjhea0** [comment]
:+1: 

Thank you!!

**Comment by wordsforthewise** [comment]
No problem, learning git and starting to contribute!

**Comment by wordsforthewise** [comment]
By the way, have you used scrapy for any projects? I'm about to start using
it for a housing website which is why I'm learning it.

Have you heard of Kimono <https://www.kimonolabs.com/>?  It's a new
scraping API thing that's supposed to be even easier, although I haven't
tried it.

**Comment by mjhea0** [comment]
I run a scraping side at http://goscrape.com. I haven't used Kimono, but I know there are a number of services out there like that. Good luck with your housing project!

**Pull request merged**
